version: '3.9'

services:
  terraform:
    image: hashicorp/terraform:1.4.0
    # Copies our terraform folder into /infra volume as the working dir, we then pass access keys to the volume
    volumes:
    - .:/infra
    working_dir: /infra
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
