include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml   # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Jobs/SAST-IaC.gitlab-ci.yml

stages:
  - validate
  - test
  - pytest
  - build
  - deploy
  - cleanup

fmt:
  extends: .terraform:fmt
  needs: []

validate:
  extends: .terraform:validate
  needs: []

build:
  extends: .terraform:build

deploy:
  extends: .terraform:deploy
  dependencies:
    - build
  environment:
    name: $TF_STATE_NAME




# Test template 
.test-template:
  stage: pytest
  image: python:3.9.6-slim-buster
  except:
    - tags
  before_script:
    - pip install poetry==1.2.2
    - poetry config virtualenvs.create false
    - poetry install

black:
  extends:
    - .test-template
  script:
    - black --check .

flake8:
  extends:
    - .test-template
  script:
    - flake8 --count .

mypy:
  extends:
    - .test-template
  script:
    - mypy .

pytest:
  extends:
    - .test-template
  services:
    - name: postgres:13.8-bullseye
      alias: database
  variables:

    # Postgresql variables
    BACKEND_DB_HOST: database
    POSTGRES_PASSWORD: backend
    POSTGRES_USER: backend
    POSTGRES_DB: backend
  script:
    - apt update
    - apt install -y wait-for-it
    - wait-for-it -t 180 $BACKEND_DB_HOST:5432
    - pytest -vv --junitxml=report.xml --cov="backend" .
    - coverage xml
  artifacts:
    when: always
    reports:
      junit: report.xml
