version: "3.9"

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
     # Grabs dist from image and adds it to volume, so we can continue hot reload
    environment:
      # Enables autoreload.
      BACKEND_RELOAD: "True"
      DEV_MODE: 1
