version: "3.9"

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    volumes:
      # Adds current directory as volume.
    - ./backend/:/app/backend/
    environment:
      # Enables autoreload.
      BACKEND_RELOAD: "True"
      DEV_MODE: 1

volumes:
  backend:
